# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-08-11 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20190811_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketingpreference',
            old_name='updated',
            new_name='update',
        ),
    ]
